<Project>
  <PropertyGroup>
    <Authors>OpenLimiter contributors</Authors>
    <Copyright>Copyright © 2026 OpenLimiter contributors</Copyright>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <VersionPrefix>0.5.0</VersionPrefix>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
