#pragma once

#define OPENLIMITER_WFP_DEVICE_NAME L"\\Device\\OpenLimiterWfp"
#define OPENLIMITER_WFP_DOS_DEVICE_NAME L"\\DosDevices\\OpenLimiterWfp"

#define OPENLIMITER_WFP_API_MAJOR 1U
#define OPENLIMITER_WFP_API_MINOR 3U

#define OPENLIMITER_WFP_CAPABILITY_PASS_THROUGH 0x00000001U
#define OPENLIMITER_WFP_CAPABILITY_FLOW_EVENTS 0x00000002U
#define OPENLIMITER_WFP_CAPABILITY_FLOW_IDENTITY 0x00000004U
#define OPENLIMITER_WFP_CAPABILITY_FLOW_PROTOCOL_DIRECTION 0x00000008U
#define OPENLIMITER_WFP_CAPABILITY_FLOW_ENDPOINTS 0x00000010U
#define OPENLIMITER_WFP_MAX_FLOW_EVENTS 64U

#define IOCTL_OPENLIMITER_WFP_GET_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_NETWORK, 0x800, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENLIMITER_WFP_GET_FLOW_EVENTS \
    CTL_CODE(FILE_DEVICE_NETWORK, 0x801, METHOD_BUFFERED, FILE_READ_DATA)

typedef struct _OPENLIMITER_WFP_CAPABILITIES {
    UINT32 Size;
    UINT32 ApiMajor;
    UINT32 ApiMinor;
    UINT32 Flags;
    UINT32 RegisteredCallouts;
    UINT32 Reserved;
    UINT64 ClassificationCount;
} OPENLIMITER_WFP_CAPABILITIES, *POPENLIMITER_WFP_CAPABILITIES;

C_ASSERT(sizeof(OPENLIMITER_WFP_CAPABILITIES) == 32);

typedef struct _OPENLIMITER_WFP_FLOW_EVENT {
    UINT64 Sequence;
    UINT64 ProcessId;
    UINT64 ApplicationIdHash;
    UINT32 IpVersion;
    UINT8 IpProtocol;
    UINT8 Direction;
    UINT16 Reserved;
    UINT8 LocalAddress[16];
    UINT8 RemoteAddress[16];
    UINT16 LocalPort;
    UINT16 RemotePort;
    UINT32 Reserved2;
} OPENLIMITER_WFP_FLOW_EVENT, *POPENLIMITER_WFP_FLOW_EVENT;

typedef struct _OPENLIMITER_WFP_FLOW_EVENT_BATCH {
    UINT32 Size;
    UINT32 Count;
    UINT64 LatestSequence;
    OPENLIMITER_WFP_FLOW_EVENT Events[OPENLIMITER_WFP_MAX_FLOW_EVENTS];
} OPENLIMITER_WFP_FLOW_EVENT_BATCH, *POPENLIMITER_WFP_FLOW_EVENT_BATCH;

C_ASSERT(sizeof(OPENLIMITER_WFP_FLOW_EVENT) == 72);
C_ASSERT(sizeof(OPENLIMITER_WFP_FLOW_EVENT_BATCH) == 4624);
